<a href="https://colab.research.google.com/github/poruuuu/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_5_Pascual_Dulay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratory 4: Matrix Operations

## Objectives
* Be familiar with the fundamental matrix operations.
* Apply the operations to solve intermediate equations.
* Apply matrix algebra in engineering solutions.

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition
The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $R$ its transpose is denoted as $R^T$. So for example:

$$R = \begin{bmatrix} 7 & -6 & -2\\11 & 4 &3 \\ -1 & 8 & 2\end{bmatrix} $$


$$R^T = \begin{bmatrix} 7 & 11 & -1\\-6 & 4 &8 \\ -2 & 3 & 2\end{bmatrix} $$


This can now be achieved programmatically by using np.transpose() or using the T method.

In [ ]:
R = np.array([
    [7 ,-6, -2],
    [11, 4, 3],
    [-1, 8, 2]
])
R

array([[ 7, -6, -2],
       [11,  4,  3],
       [-1,  8,  2]])

In [ ]:
RT1 = np.transpose(R)
RT1

array([[ 7, 11, -1],
       [-6,  4,  8],
       [-2,  3,  2]])

In [ ]:
RT2 = R.T
RT2

array([[ 7, 11, -1],
       [-6,  4,  8],
       [-2,  3,  2]])

In [ ]:
np.array_equiv(RT1, RT2)

True

In [ ]:
M = np.array([
    [-12,-11,8,-9],
    [0,7,23,14],
    [3,17,-1,0]
])
M.shape

(3, 4)

In [ ]:
np.transpose(M).shape

(4, 3)

In [ ]:
M.T.shape

(4, 3)

### Try to create your own matrix (non-squares) to test transposition.

In [ ]:
## Try out your code here.
Z=np.array([
    [-7,0],
    [42,-31],
    [6,19],
    [24,-9]
])
Z.shape

(4, 2)

In [ ]:
np.transpose(Z).shape

(2, 4)

In [ ]:
Z.T.shape

(2, 4)

In [ ]:
ZT = Z.T
ZT

array([[ -7,  42,   6,  24],
       [  0, -31,  19,  -9]])

## Dot Product / Inner Product
In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $A$ and $P$:

If we have two matrices $A$ and $P$:

$$A = \begin{bmatrix}A_{(0,0)}&A_{(0,1)}\\ A_{(1,0)}&A_{(1,1)}\end{bmatrix}, P = \begin{bmatrix}P_{(0,0)}&P_{(0,1)}\\ P_{(1,0)}&P_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$A \cdot P= \begin{bmatrix} A_{(0,0)}*P_{(0,0)} + A_{(0,1)}*P_{(1,0)} & A_{(0,0)}*P_{(0,1)} + A_{(0,1)}*P_{(1,1)} \\  A_{(1,0)}*P_{(0,0)} + A_{(1,1)}*P_{(1,0)} & A_{(1,0)}*P_{(0,1)} + A_{(1,1)}*P_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$A = \begin{bmatrix}-2&7\\ 9&-17\end{bmatrix}, P = \begin{bmatrix}31&-8\\ -4&25\end{bmatrix}$$

In [ ]:
A = np.array([
    [-2,7],
    [9,-17]
])
P = np.array([
    [31,-8],
    [-4,25]
])

In [ ]:
np.array_equiv(A, P)

False

In [ ]:
np.dot(A,P)

array([[ -90,  191],
       [ 347, -497]])

In [ ]:
A.dot(P)

array([[ -90,  191],
       [ 347, -497]])

In [ ]:
A @ P

array([[ -90,  191],
       [ 347, -497]])

In [ ]:
np.matmul(A,P)

array([[ -90,  191],
       [ 347, -497]])

In [ ]:
E = np.array([
    [-4,-1,-5,13],
    [0,0,1,-22],
    [3,9,-14,-5],
    [-2,1,0,0]
])
H = np.array([
    [2,0,4,-3],
    [17,-7,7,12],
    [-1,7,17,0],
    [0,0,0,-28]
])

In [ ]:
E @ H

array([[ -20,  -28, -108, -364],
       [  -1,    7,   17,  616],
       [ 173, -161, -163,  239],
       [  13,   -7,   -1,   18]])

In [ ]:
E.dot(H)

array([[ -20,  -28, -108, -364],
       [  -1,    7,   17,  616],
       [ 173, -161, -163,  239],
       [  13,   -7,   -1,   18]])

In [ ]:
np.matmul(E, H)

array([[ -20,  -28, -108, -364],
       [  -1,    7,   17,  616],
       [ 173, -161, -163,  239],
       [  13,   -7,   -1,   18]])

In [ ]:
np.dot(E, H)

array([[ -20,  -28, -108, -364],
       [  -1,    7,   17,  616],
       [ 173, -161, -163,  239],
       [  13,   -7,   -1,   18]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules

### Rule 1: The inner dimensions of the two matrices in question must be the same.

Given the following matrices:

$$D = \begin{bmatrix}-7&15&0\\8&14&3\\3&-8&-14\\-11&-2&0\end{bmatrix}, O = \begin{bmatrix}-4&18&0\\-5&1&0\\3&1&-8\\-9&7&-11\end{bmatrix}, K = \begin{bmatrix}9&-6&0&22\\16&7&0&-7\\-3&14&-3&0\end{bmatrix}$$

So in this case $D$ has a shape of $(3,3)$, $O$ has a shape of $(3,2)$ and $K$ has a shape of $(3,4)$. So the only matrix pairs that is eligible to perform dot product is matrices $D \cdot K$, or $O \cdot K$.  

In [ ]:
D = np.array([
    [-7,15,0],
    [8,14,3],
    [3,-8,-14],
    [-11,-2,0]
])
O = np.array([
    [-4,18,0],
    [-5,1,0],
    [3,1,-8],
    [-9,7,-11]
])
K= np.array([
    [9,-6,0,22],
    [16,7,0,-7],
    [-3,14,-3,0]
])
print(D.shape)
print(O.shape)
print(K.shape)

(4, 3)
(4, 3)
(3, 4)


In [ ]:
D @ K

array([[ 177,  147,    0, -259],
       [ 287,   92,   -9,   78],
       [ -59, -270,   42,  122],
       [-131,   52,    0, -228]])

In [ ]:
O @ K

array([[ 252,  150,    0, -214],
       [ -29,   37,    0, -117],
       [  67, -123,   24,   59],
       [  64,  -51,   33, -247]])

In [ ]:
D @ O.T

array([[ 298,   50,   -6,  168],
       [ 220,  -26,   14,   -7],
       [-156,  -23,  113,   71],
       [   8,   53,  -35,   85]])

In [ ]:
N = np.array([
    [8,16,-22],
    [74,11,0]
])
U = np.array([
    [4,0,0],
    [0,-11,8]
])
print(N.shape)
print(U.shape)

(2, 3)
(2, 3)


In [ ]:
U.T @ N

array([[  32,   64,  -88],
       [-814, -121,    0],
       [ 592,   88,    0]])

In [ ]:
U @ N.T

array([[  32,  296],
       [-352, -121]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:

 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [7,-63],
    [32,-30]
])
B = np.array([
    [6,6],
    [-2,1]
])
C = np.array([
    [81,33],
    [-41,0]
])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
A.dot(np.eye(2))

array([[  7., -63.],
       [ 32., -30.]])

In [ ]:
np.array_equal(A@B, B@A)

False

In [ ]:
DULAY = A @ (B @ C)
DULAY

array([[14469,  5544],
       [13770,  8316]])

In [ ]:
PASCUAL = (A @ B) @ C
PASCUAL

array([[14469,  5544],
       [13770,  8316]])

In [ ]:
np.array_equal(DULAY, C)

False

In [ ]:
np.array_equiv(DULAY, PASCUAL)

True

In [ ]:
A @ C

array([[3150,  231],
       [3822, 1056]])

In [ ]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0.],
       [0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0.]
 [0. 0.]]


True

## Determinant
A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. 

The determinant of some matrix $S$ is denoted as $det(S)$ or $|S|$. So let's say $S$ is represented as:
$$S = \begin{bmatrix}S_{(0,0)}&S_{(0,1)}\\S_{(1,0)}&S_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|S| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$S = \begin{bmatrix}-5&0\\6&-11\end{bmatrix}, |S| = 55$$



In [ ]:
S = np.array([
    [-5,0],
    [6,-11]
])
np.linalg.det(S)

54.999999999999964

In [ ]:
V = np.array([
              [8,-9,3],
              [9,-14,20],
              [1,-1,0]
])
np.linalg.det(V)

-5.00000000000001

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
J = np.array([
    [-81,2,-45,31],
    [0,51,33,6],
    [14,-8,8,36],
    [-55,71,4,9]
])
np.linalg.det(J)

-1401444.0000000014

## Inverse
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices.

In [ ]:
W = np.array([
    [-7,11],
    [-45, -4]
])

np.array(W @ np.linalg.inv(W), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
I = np.array([
              [15,-2,3],
              [1,-5,9],
              [-6,-1,-11]
])
F = np.linalg.inv(I)
F

array([[ 0.06715635, -0.02623295, -0.00314795],
       [-0.04512067, -0.15424974, -0.13850997],
       [-0.03252886,  0.02833158, -0.07660021]])

In [ ]:
I @ F

array([[ 1.00000000e+00, -2.42861287e-17, -1.38777878e-17],
       [ 0.00000000e+00,  1.00000000e+00,  6.93889390e-17],
       [ 5.55111512e-17, -3.46944695e-18,  1.00000000e+00]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [4,75,-11,32,6],
    [17,168,-55,7,4],
    [36,-123,14,3,6],
    [111,-7,-63,32,2],
    [1,0,0,-87,14]
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
squad = np.array([
    [2.9822,3.4152,0.2369],
    [9.4587,4.1259,3.1258],
    [3.6785,2.6587,2.1458]
])
weights = np.array([
    [6.5478,3.1235,7.2548]
])
p_grade = squad @ weights.T
p_grade

array([[31.91288848],
       [97.49797835],
       [47.95788159]])

## Activity
Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
np.array([])

array([], dtype=float64)

In [ ]:
## Function area
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


In [ ]:
## Comutativity is not applicable (A⋅B≠B⋅A)
def mat_prop(firstArray, secondArray):
  if len(firstArray) == len(secondArray):
    com = M @ A
    tat = A @ M
    print(f'M⋅A:\n{com}\n\nA⋅M:\n{tat}\n\nEqual:{np.array_equal(M@A, A@M)}')
    print("\nTherefore, M ⋅ A is ≠ to A ⋅ M.")
  else:
    print("Matrices are not viable for operation.")
    
M = np.array([
              [3,1,2,4],
              [2,4,6,8],
              [3,0,2,-1],
              [8,0,0,-3]
])

A = np.array([
              [1,1,1,-1],
              [2,4,6,8],
              [3,0,2,-1],
              [8,0,0,-3]
])

mat_prop(M,A)

M⋅A:
[[ 43   7  13  -9]
 [ 92  18  38   0]
 [  1   3   7  -2]
 [-16   8   8   1]]

A⋅M:
[[ 0  5 10 14]
 [96 18 40 10]
 [ 7  3 10 13]
 [ 0  8 16 41]]

Equal:False

Therefore, M ⋅ A is ≠ to A ⋅ M.


In [ ]:
##Associative Law[A⋅(B⋅C)=(A⋅B)⋅C]
def mat_prop(firstArray, secondArray, thirdArray):
  if len(firstArray) == len(secondArray) == len(thirdArray):
    ass = R@(O@S)
    oci = (R@O)@S
    print(f'R⋅(O⋅S):\n{ass}\n\n(R⋅O)⋅S:\n{oci}\n\nEqual:{np.array_equal(ass, oci)}\n\nEquivalent:{np.array_equiv(ass, oci)}')
    print("\nTherefore, Associative Law is applicable")
  else:
    print("Matrices are not viable for operation.")

R = np.array([
              [3,1,2,4],
              [2,4,6,8],
              [3,0,2,-1],
              [8,0,0,-3]
])

O = np.array([
              [1,1,1,-1],
              [2,4,6,8],
              [3,0,2,-1],
              [8,0,0,-3]
])

S = np.array([
              [0,3,2,4],
              [5,4,3,2],
              [3,2,-1,0],
              [3,-2,0,5]
])

mat_prop(R,O,S)

R⋅(O⋅S):
[[ 47 201  94 141]
 [204 424 200 404]
 [ 30  33   4   0]
 [ 67  -2 -16 -43]]

(R⋅O)⋅S:
[[ 47 201  94 141]
 [204 424 200 404]
 [ 30  33   4   0]
 [ 67  -2 -16 -43]]

Equal:True

Equivalent:True

Therefore, Associative Law is applicable


In [ ]:
##Distributive Law is applicable [A⋅(B+C)=A⋅B+A⋅C]
def mat_prop(firstArray, secondArray, thirdArray):
  if len(firstArray) == len(secondArray) == len(thirdArray):
    dis = P@(A+S)
    tri = (P@A)+(P@S)
    print(f'P⋅(A+S):\n{dis}\n\nP⋅A+P⋅S:\n{tri}\n\nEqual:{np.array_equal(dis, tri)}\n\nEquivalent:{np.array_equiv(dis, tri)}')
    print("\nTherefore, Distributive Law is applicable")
  else:
    print("Matrices are not viable for operation.")

P = np.array([
              [3,1,2,4],
              [2,4,2,1],
              [3,0,2,-1],
              [4,2,0,-3]
])

A = np.array([
              [0,1,-1,0],
              [5,10,2,15],
              [3,0,2,-1],
              [8,15,4,-3]
])

S = np.array([
              [0,1,2,4],
              [9,8,7,6,],
              [-2,-3,-4,-5],
              [3,6,9,3]
])

mat_prop(P,A,S)

P⋅(A+S):
[[ 60 102  60  21]
 [ 69  91  47  80]
 [ -9 -21 -14   0]
 [ -5 -19 -17  58]]

P⋅A+P⋅S:
[[ 60 102  60  21]
 [ 69  91  47  80]
 [ -9 -21 -14   0]
 [ -5 -19 -17  58]]

Equal:True

Equivalent:True

Therefore, Distributive Law is applicable


In [ ]:
##[(B+C)⋅A=B⋅A+C⋅A]
def mat_prop(firstArray, secondArray, thirdArray):
  if len(firstArray) == len(secondArray) == len(thirdArray):
    dis = (A+S)@P
    tri = (A@P)+(S@P)
    print(f'(A+S)@P:\n{dis}\n\nA@P)+(S@P)::\n{tri}\n\nEqual:{np.array_equal(dis, tri)}\n\nEquivalent:{np.array_equiv(dis, tri)}')
    print("\nTherefore, the statement (B+C)⋅A=B⋅A+C⋅A is true")
  else:
    print("Matrices are not viable for operation.")

mat_prop(P,A,S)

(A+S)@P:
[[ 23  16   6 -11]
 [189 128  82   2]
 [-33 -23  -8  21]
 [114  95  90  52]]

A@P)+(S@P)::
[[ 23  16   6 -11]
 [189 128  82   2]
 [-33 -23  -8  21]
 [114  95  90  52]]

Equal:True

Equivalent:True

Therefore, the statement (B+C)⋅A=B⋅A+C⋅A is true


In [ ]:
##Multiplicative Identity [A⋅I=A/I⋅A=A]
def mat_prop(firstArray, secondArray):
  if len(firstArray) == len(secondArray):
    Ide = A@I
    ide = A 
    print(f'A⋅I:\n{Ide}\n\nA:\n{ide}\n\nEqual:{np.array_equal(Ide, ide)}\n\nEquivalent:{np.array_equiv(Ide, ide)}')
    print("\nTherefore, the statement A⋅I=A/I⋅A=A is true")
  else:
    print("Matrices are not viable for operation.")

A = np.array([
              [3,5,6,-1],
              [2,4,6,8],
              [3,4,2,3],
              [6,12,-4,3]
])

I = np.identity(4)

mat_prop(A, I)

A⋅I:
[[ 3.  5.  6. -1.]
 [ 2.  4.  6.  8.]
 [ 3.  4.  2.  3.]
 [ 6. 12. -4.  3.]]

A:
[[ 3  5  6 -1]
 [ 2  4  6  8]
 [ 3  4  2  3]
 [ 6 12 -4  3]]

Equal:True

Equivalent:True

Therefore, the statement A⋅I=A/I⋅A=A is true


In [ ]:
## A⋅∅=∅
def mat_prop(firstArray, secondArray):
  if len(firstArray) == len(secondArray):
    Zer = M@R 
    print(f'M ⋅ R:\n{Zer}')
    print("\nTherefore, the statement A⋅∅=∅ is true")
  else:
    print("Matrices are not viable for operation.")

M = np.array([
              [30,20,10,50],
              [43,55,61,70],
              [44,5,33,22],
              [10,20,30,40]
])

R = np.zeros((4,4))

mat_prop(M,R)

M ⋅ R:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Therefore, the statement A⋅∅=∅ is true
