<a href="https://colab.research.google.com/github/poruuuu/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3_Pascual_Dulay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE 
## Assignment 3: Matrix in Python

## Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.


## Discussion

In [70]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


### Matrices
A sequence of scalars or vectors makes up a matrix. They're commonly kept as a collection of arrays in code. Matrixes are also known as multidimensional arrays. Matrices may also be used to represent multidimensional equations or multiple complex equations, spanning from two to hundreds or thousands of variables.

Let's say for example you have ***M***, ***A*** and ***R*** as system of equations.

$$
M = \left\{
    \begin{array}\
        x + y \\ 
        23x - 7y
    \end{array}
\right. \\
A = \left\{
    \begin{array}\
        x+554y+z \\ 
        71x +9y -20z \\
        -56x -2y -89z
    \end{array}
\right. \\
R = \left\{
   \begin{array}\
        33w-21x+92y-z \\
        w+ 11x -7y +32z \\
        24w -1x + 7y - 74z
    \end{array}
\right.
$$

We could see that ***M*** is a system of **2 equations with 2 parameters**. While ***A*** is a system of **3 equations with 3 parameters**. ***R*** is a **4 system of equations with 4 parameters**. We can represent them as matrices as:

$$
M=\begin{bmatrix} 1 & 1 \\ 23 & {-7}\end{bmatrix} \\
A=\begin{bmatrix} 1 & 554 & 1 \\ 71 & 9 & -20 \\ -56 & -2 & -89\end{bmatrix}\\
R=\begin{bmatrix} 33 & -21 & 92 & -1 \\ 1 & 11 & -7 & 32 \\ 24 & -1 & 7 & -74\end{bmatrix}
$$


### Declaring Matrices

The elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas ***A*** is matrix consisting of elements denoted by aij. Denoted by *i* is the number of rows in the matrix while *j* stands for the number of columns. Do note that the size of a matrix is ***i x j***.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using **shape, dimensions** and **size** attributes, we'll use them to analyze these matrices.

In [71]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [72]:
## Declaring a 2 x 2 matrix
R = np.array([
    [-361, -2],
    [7, 11],
])
describe_mat(R)

Matrix:
[[-361   -2]
 [   7   11]]

Shape:	(2, 2)
Rank:	2



In [73]:
O = np.array([
    [-4,81],
    [6,-11]
])
describe_mat(O)


Matrix:
[[ -4  81]
 [  6 -11]]

Shape:	(2, 2)
Rank:	2



In [74]:
## Declaring a 3 x 2 matrix
S = np.array([
    [-87, 213],
    [595, 7],
    [-45, 8]
])
describe_mat(S)


Matrix:
[[-87 213]
 [595   7]
 [-45   8]]

Shape:	(3, 2)
Rank:	2



In [75]:
H = np.array([
    [-41,71,55,4,-9]
    ])
describe_mat(H)


Matrix:
[[-41  71  55   4  -9]]

Shape:	(1, 5)
Rank:	2



### Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them

#### According to Shape

##### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be 1 x j and column matrices be i x 1.

In [76]:
## Declaring Row Matrix

rowmatrix1D = np.array([
    7, -11, 74, -1
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [7,-11,74, -1]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[  7 -11  74  -1]

Shape:	(4,)
Rank:	1

Matrix:
[[  7 -11  74  -1]]

Shape:	(1, 4)
Rank:	2



In [77]:
## Declaring a column matrix

col_mat = np.array([
    [5],
    [8],
    [7],
    [-25]
]) ## this is a 2-D Matrix with a shape of (4,1)
describe_mat(col_mat)


Matrix:
[[  5]
 [  8]
 [  7]
 [-25]]

Shape:	(4, 1)
Rank:	2



##### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if i = j. We can tweak our matrix descriptor function to determine square matrices.

In [78]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [79]:
square_mat = np.array([
    [-5,74,9],
    [8,7,20],
    [-2,4,9]
])

non_square_mat = np.array([
    [55,-7,23],
    [2,7,31]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[-5 74  9]
 [ 8  7 20]
 [-2  4  9]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[55 -7 23]
 [ 2  7 31]]

Shape:	(2, 3)
Rank:	2
Is Square: False



#### According to Element Values

##### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix. Adding a null matrix to any other matrix produces the same outcome, a null matrix is also known as the additive identity of the provided matrix.

In [80]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')


In [81]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


##### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0. It also acts as the additive identification of the cumulative group of matrices, and is represented by a notation or subscripts according to the matrix's dimension.

In [82]:
zero_mat_row = np.zeros((1,9))
zero_mat_sqr = np.zeros((4,4))
zero_mat_rct = np.zeros((5,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')


Zero Row Matrix: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


##### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [83]:
ones_mat_row = np.ones((1,8))
ones_mat_sqr = np.ones((6,6))
ones_mat_rct = np.ones((7,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1. 1. 1. 1. 1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


##### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.Usually, the phrase refers to square matrices. The primary diagonal's components can be either zero or nonzero.

In [84]:
np.array([
    [-4,0,0],
    [0,64,0],
    [0,0,71]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[-4,  0,  0],
       [ 0, 64,  0],
       [ 0,  0, 71]])

In [85]:
d = np.diag([4,-11,61,10])
#d.shape[0] == d.shape[1]
d

array([[  4,   0,   0,   0],
       [  0, -11,   0,   0],
       [  0,   0,  61,   0],
       [  0,   0,   0,  10]])

##### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [86]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal.

In [88]:
np.array([
    [-42,3,22,-7],
    [0,3,14,-4],
    [0,0,3,10],
    [0,0,0,74]
])

array([[-42,   3,  22,  -7],
       [  0,   3,  14,  -4],
       [  0,   0,   3,  10],
       [  0,   0,   0,  74]])

In [89]:
F = np.array([
              [4, 6, -8, 5, 11],
              [4, 6, -8, 5, 11],
              [4, 6, -8, 5, 11],
              [4, 6, -8, 5, 11],
              [4, 6, -8, 5, 11],
])
np.triu(F)

array([[ 4,  6, -8,  5, 11],
       [ 0,  6, -8,  5, 11],
       [ 0,  0, -8,  5, 11],
       [ 0,  0,  0,  5, 11],
       [ 0,  0,  0,  0, 11]])

##### Lower Triangular Matrix
A lower triangular matrix is a matrix that has no values above the diagonal.

In [90]:
np.tril(F)

array([[ 4,  0,  0,  0,  0],
       [ 4,  6,  0,  0,  0],
       [ 4,  6, -8,  0,  0],
       [ 4,  6, -8,  5,  0],
       [ 4,  6, -8,  5, 11]])

In [91]:
np.array([
          [2,0,0],
          [-10,4,0],
          [22,1,-85]
])

array([[  2,   0,   0],
       [-10,   4,   0],
       [ 22,   1, -85]])

##Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$

In [92]:
θ = ([5,3,-1])
θ

[5, 3, -1]

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


In [93]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [94]:
A = np.array([
      [1,2,1],
      [0,4,-3],
      [0,0,10]
])
describe_mat(A)

Matrix:
[[ 1  2  1]
 [ 0  4 -3]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [95]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$
G=\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}
$$


$$
G = \left\{\begin{array}
1x_1 + 7x_2 + 8x_3\\
2x_1 + 2x_2 - 2x_3\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$


4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [96]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
G = \left\{\begin{array}
1x_1 \\
2x_1 + 2x_2\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$
\
$$
G=\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}
$$

##Matrix Algebra

###Addition

In [97]:
A = np.array([
    [13,5,3],
    [-9,6,7],
    [7,-3,4]
])
B = np.array([
    [9,14,1],
    [1,11,0],
    [2,-4,-2]
])
A+B

array([[22, 19,  4],
       [-8, 17,  7],
       [ 9, -7,  2]])

In [98]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[15,  7,  5],
       [-7,  8,  9],
       [ 9, -1,  6]])

###Subtraction

In [99]:
A-B

array([[  4,  -9,   2],
       [-10,  -5,   7],
       [  5,   1,   6]])

In [100]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

###Element-wise Multiplication

In [101]:
A*B
np.multiply(A,B)

array([[117,  70,   3],
       [ -9,  66,   0],
       [ 14,  12,  -8]])

In [102]:
2*A

array([[ 26,  10,   6],
       [-18,  12,  14],
       [ 14,  -6,   8]])

In [103]:
alpha=10**-12
A/(alpha+B)

array([[ 1.44444444e+00,  3.57142857e-01,  3.00000000e+00],
       [-9.00000000e+00,  5.45454545e-01,  7.00000000e+12],
       [ 3.50000000e+00,  7.50000000e-01, -2.00000000e+00]])

In [104]:
np.add(A,B)

array([[22, 19,  4],
       [-8, 17,  7],
       [ 9, -7,  2]])

##Activity

###Task 1
Create a function named mat_desc()  that througouhly describes a matrix, it should:

  1. Displays the shape, size, and rank of the matrix.
  2. Displays whether the matrix is square or non-square.
  3. Displays whether the matrix is an empty matrix.
  4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [105]:
## Function area
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [106]:
def mat_desc(matrix):
    if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False 
      print(f'Matrix:\n{matrix}\n\nDescription:\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nSquare: {is_square}\n\nSize:\t{matrix.size}')
    else:
      print('Matrix has no contents')

In [107]:
## Matrix declarations
P = zero_mat_row = np.zeros((3,3))
U = ones_mat_rct = np.ones((4,4))

In [108]:
M = np.array([
              [33,44,49],
              [55,44,32],
              [23,18,20],
              [10,20,30]
])
A = np.array([
              [10,20,30,40,3],
              [5,10,15,20,6],
              [60,50,33,78,9],
              [66,44,33,44,12],
              [66,11,22,88,18]
])
R = np.array([])

In [109]:
## Test Areas
mat_desc(M)

Matrix:
[[33 44 49]
 [55 44 32]
 [23 18 20]
 [10 20 30]]

Description:

Shape:	(4, 3)
Rank:	2
Square: False

Size:	12


In [110]:
mat_desc(A)

Matrix:
[[10 20 30 40  3]
 [ 5 10 15 20  6]
 [60 50 33 78  9]
 [66 44 33 44 12]
 [66 11 22 88 18]]

Description:

Shape:	(5, 5)
Rank:	2
Square: True

Size:	25


In [111]:
mat_desc(R)

Matrix has no contents


In [112]:
mat_desc(P)

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Description:

Shape:	(3, 3)
Rank:	2
Square: True

Size:	9


In [113]:
mat_desc(U)

Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Description:

Shape:	(4, 4)
Rank:	2
Square: True

Size:	16


### Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

  1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
  2. Returns the sum of the matrices.
  3. Returns the difference of the matrices.
  4. Returns the element-wise multiplication of the matrices.
  5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [114]:
## Function area
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


In [115]:
def mat_operations(firstArray, secondArray):
  if len(firstArray) == len(secondArray):
    sum = firstArray + secondArray
    dif = firstArray - secondArray
    div = firstArray / secondArray
    mul = firstArray * secondArray
    print(f'Sum:\n{sum}\n\nDiferrence:\n{dif}\n\nQuotient:\n{div}\n\nProduct:\n{mul}')
    print("\nTherefore, matrices are viable for operation.")
  else:
    print("Matrices are not viable for operation.")


In [116]:
## Mat declarations
F = np.array([
    [1,3,2,5],
    [-13,47,-5,31],
    [1,2,-2,67],
    [4,-8,-21,30]
])
K = np.array([
    [74,9,-6,5],
    [16,11,10,-7],
    [73,-4,-7,10],
    [-9,47,-8,-8]
])
E = np.array([
              [10,20,30,11],
              [12,-13,-15,14],
              [23,-1,3,7],
              [5,-9,9,1]
])
G = np.array([
              [1,2,3,10],
              [12,-2,15,4],
              [2,1,1,6],
              [5,1,18,-7]
])
O = np.array([
              [1,2,3,10],
              [12,-2,15,4],
              [2,1,0,6],
              [5,0,18,-7]
])
Z = np.array([
              [1,2,3,10],
              [12,-2,15,4],
              [2,1,0,6],
])
Q = np.array([
              [0,-1,-5-6,10],
              [12,3,-15,14,9],
              [5,5,-5,3,6]
])
T = np.array([
              [3,6,9],
              [2,4,6],
              [2,1,0],
              [5,10,15]
])
B = np.array([
              [4,8,12],
              [6,12,-18],
              [7,14,21],
              [8,-16,24]
])
R = np.array([
              [0,-1,-5-6,10],
              [12,3,-15,14,9],
              [5,5,-5,3,6],
              [2,2,0,2,2]
    ])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:40: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:58: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


In [117]:
## Test Areas
mat_operations(F, K)

Sum:
[[ 75  12  -4  10]
 [  3  58   5  24]
 [ 74  -2  -9  77]
 [ -5  39 -29  22]]

Diferrence:
[[-73  -6   8   0]
 [-29  36 -15  38]
 [-72   6   5  57]
 [ 13 -55 -13  38]]

Quotient:
[[ 0.01351351  0.33333333 -0.33333333  1.        ]
 [-0.8125      4.27272727 -0.5        -4.42857143]
 [ 0.01369863 -0.5         0.28571429  6.7       ]
 [-0.44444444 -0.17021277  2.625      -3.75      ]]

Product:
[[  74   27  -12   25]
 [-208  517  -50 -217]
 [  73   -8   14  670]
 [ -36 -376  168 -240]]

Therefore, matrices are viable for operation.


In [118]:
mat_operations(G,E)

Sum:
[[ 11  22  33  21]
 [ 24 -15   0  18]
 [ 25   0   4  13]
 [ 10  -8  27  -6]]

Diferrence:
[[ -9 -18 -27  -1]
 [  0  11  30 -10]
 [-21   2  -2  -1]
 [  0  10   9  -8]]

Quotient:
[[ 0.1         0.1         0.1         0.90909091]
 [ 1.          0.15384615 -1.          0.28571429]
 [ 0.08695652 -1.          0.33333333  0.85714286]
 [ 1.         -0.11111111  2.         -7.        ]]

Product:
[[  10   40   90  110]
 [ 144   26 -225   56]
 [  46   -1    3   42]
 [  25   -9  162   -7]]

Therefore, matrices are viable for operation.


In [119]:
mat_operations(N,O)

Matrices are not viable for operation.


In [120]:
mat_operations(Z,R)

Matrices are not viable for operation.


In [121]:
mat_operations(T, B)

Sum:
[[  7  14  21]
 [  8  16 -12]
 [  9  15  21]
 [ 13  -6  39]]

Diferrence:
[[ -1  -2  -3]
 [ -4  -8  24]
 [ -5 -13 -21]
 [ -3  26  -9]]

Quotient:
[[ 0.75        0.75        0.75      ]
 [ 0.33333333  0.33333333 -0.33333333]
 [ 0.28571429  0.07142857  0.        ]
 [ 0.625      -0.625       0.625     ]]

Product:
[[  12   48  108]
 [  12   48 -108]
 [  14   14    0]
 [  40 -160  360]]

Therefore, matrices are viable for operation.


## Conclusion
For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".